rtspAddress: :8554
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -framerate 25 -video_size 640x480 -i /dev/video0 -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:8554/cam
    runOnInitRestart: yes
